//https://afternoon-beyond-65238.herokuapp.com
###
GET http://127.0.0.1:8000/api/aws-sms-test HTTP/1.1
Content-Type: application/json
Accept: application/json

###
GET http://127.0.0.1:8000/api/crone-job-test HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|5vthuk5GMeqkj8izK08MDiQFLObokSS6vyI8AR8N

###
POST http://127.0.0.1:8000/api/create-admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95

{
    "user_id": 3,
    "group_id": 1
}
####
GET http://127.0.0.1:8000/api/admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95
###
POST http://127.0.0.1:8000/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "jay@demo.com",
    "password": "password"
}

###
POST http://127.0.0.1:8000/api/admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95

{
    "name": "Imrana A. Bala",
    "phone_number": "07066352428",
    "email": "jay@demo.com",
    "password": "password",
    "password_confirmation": "password",
    "gender": "Male",
    "dob": "2022-06-21"
    //"group_id": 1
}
###
GET http://127.0.0.1:8000/api/birthdays-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95

###
GET http://127.0.0.1:8000/api/users-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95
###
GET http://127.0.0.1:8000/api/admin-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95
###
GET http://127.0.0.1:8000/api/admin/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95
###
DELETE http://127.0.0.1:8000/api/admin/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95
###
PUT http://127.0.0.1:8000/api/admin/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95

{
    "name": "ABDULJAWAD IBRAHIM Narumah",
    "email": "jawadNarumahs@gmail.com",
    "phone_number": "07035460599",
    "gender": "Male",
    "dob": "2022-06-23",
    "group_id": 1
}
###
GET http://127.0.0.1:8000/api/birthdays HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95
###
GET http://127.0.0.1:8000/api/group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95

###
GET http://127.0.0.1:8000/api/group-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95

###
POST http://127.0.0.1:8000/api/group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95

{
    "group_name": "Jay",
    "admin_id": 3
}

###
GET http://127.0.0.1:8000/api/group/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95
###
PUT http://127.0.0.1:8000/api/group/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|rfP36jHsT2ZA5lRFxR5EhoqkrSR6N8fMHIBjDFQ4

{
    "group_name": "JayConcepts"
}
###
DELETE http://127.0.0.1:8000/api/group/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95
###
GET http://127.0.0.1:8000/api/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|SPYOzLd0FRKJUtWfrIJYGyIfvaOb11tm7SrjNg8C
###
GET http://127.0.0.1:8000/api/user-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|SPYOzLd0FRKJUtWfrIJYGyIfvaOb11tm7SrjNg8C
###
GET http://127.0.0.1:8000/api/birthday HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|SPYOzLd0FRKJUtWfrIJYGyIfvaOb11tm7SrjNg8C
###
GET http://127.0.0.1:8000/api/birthday-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|SPYOzLd0FRKJUtWfrIJYGyIfvaOb11tm7SrjNg8C
###
GET http://127.0.0.1:8000/api/admin-groups HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|SPYOzLd0FRKJUtWfrIJYGyIfvaOb11tm7SrjNg8C
###
POST http://127.0.0.1:8000/api/add-member HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|KR0ksZc0ufGAaHxbRAuOI0CxYEdbzgu6awOis0UI

{
    "profile_id": 2,
    "group_id": 2
}
###
POST http://127.0.0.1:8000/api/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|KR0ksZc0ufGAaHxbRAuOI0CxYEdbzgu6awOis0UI

{
    "name": "Imrana A. Bala",
    "phone_number": "07066352211",
    "email": "imee4332@demo.com",
    "gender": "Male",
    "dob": "2022-06-20",
    "group_id": 1
}

###
PUT http://127.0.0.1:8000/api/user/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|KR0ksZc0ufGAaHxbRAuOI0CxYEdbzgu6awOis0UI

{
    "name": "ABDULJAWAD IBRAHIM",
    "email": "jawads12rumahh@gmail.com",
    "phone_number": "07035460539",
    "gender": "Male",
    "dob": "2022-06-01"

}

###
GET http://127.0.0.1:8000/api/user/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|KR0ksZc0ufGAaHxbRAuOI0CxYEdbzgu6awOis0UI

###
DELETE http://127.0.0.1:8000/api/user/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|KR0ksZc0ufGAaHxbRAuOI0CxYEdbzgu6awOis0UI

###
POST http://127.0.0.1:8000/api/logout HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 8|TcJpcuIUd29njBTAexpA1u2lDqe1knoVMtXcBGHb
###
POST http://127.0.0.1:8000/api/create-admin HTTP/1.1
ontent-Type: application/json
Accept: application/json
Authorization: Bearer 1|pGvfaVnFzpRBrzG0iwApoWxe2ryq9GPJOyWVl0rg

{
    "group_id": 1,
    "profile_id": 7,
    "password": "password"
}

###
POST http://127.0.0.1:8000/api/add-member HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|pGvfaVnFzpRBrzG0iwApoWxe2ryq9GPJOyWVl0rg

{
    "email": "theresa.romaguera@example.com",
    "group_id": 3
}

###
GET http://127.0.0.1:8000/api/admin-group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|KR0ksZc0ufGAaHxbRAuOI0CxYEdbzgu6awOis0UI
###
GET http://127.0.0.1:8000/api/admin-profile HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|KR0ksZc0ufGAaHxbRAuOI0CxYEdbzgu6awOis0UI

###
GET http://127.0.0.1:8000/api/search HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|pGvfaVnFzpRBrzG0iwApoWxe2ryq9GPJOyWVl0rg

{
    "search": "jawad"
}
